package main.java.cn.guzx.mapper;

import java.util.List;
import main.java.cn.guzx.model.TestDemo;
import main.java.cn.guzx.model.TestDemoExample;
import org.apache.ibatis.annotations.Param;

public interface TestDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    long countByExample(TestDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int deleteByExample(TestDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int insert(TestDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int insertSelective(TestDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    List<TestDemo> selectByExample(TestDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    TestDemo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") TestDemo record, @Param("example") TestDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int updateByExample(@Param("record") TestDemo record, @Param("example") TestDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int updateByPrimaryKeySelective(TestDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_demo
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    int updateByPrimaryKey(TestDemo record);
}