package main.java.cn.guzx.model;

public class TestDemo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_demo.id
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_demo.name
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_demo.remark
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_demo.id
     *
     * @return the value of test_demo.id
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_demo.id
     *
     * @param id the value for test_demo.id
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_demo.name
     *
     * @return the value of test_demo.name
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_demo.name
     *
     * @param name the value for test_demo.name
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_demo.remark
     *
     * @return the value of test_demo.remark
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_demo.remark
     *
     * @param remark the value for test_demo.remark
     *
     * @mbg.generated Wed Mar 04 20:14:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}